@Api_HostAddress = http://localhost:5000/api

GET {{Api_HostAddress}}/generate?n=2
Accept: application/json

###

POST {{Api_HostAddress}}/predict
Accept: application/json
Content-Type: application/json

[
  {
    "loanAmount": 456500,
    "rateOfInterest": 3.74,
    "upfrontCharges": 0,
    "term": 360,
    "propertyValue": 608000,
    "income": 0,
    "creditScore": 752,
    "age": "55-64",
    "region": "south",
    "debtToIncomeRatio": 29
  },
  {
    "loanAmount": 346500,
    "rateOfInterest": 4.025,
    "upfrontCharges": 60000,
    "term": 360,
    "propertyValue": 1808000,
    "income": 3060,
    "creditScore": 773,
    "age": ">74",
    "region": "North",
    "debtToIncomeRatio": 61
  }
]